const FETECH_ALL_POSTS = "FETECH_ALL_POSTS";
const CREATE_POST = "CREATE_POST";
const UPDATE_POST = "UPDATE_POST";
const DELETE_POST = "DELETE_POST";
const LIKE_POST = "LIKE_POST";
const AUTH = "AUTH";
const LOGOUT = "LOGOUT";
const SIGN_UP = "SIGN_UP";
const SIGN_IN = "SIGN_IN";

export {
  FETECH_ALL_POSTS,
  CREATE_POST,
  UPDATE_POST,
  DELETE_POST,
  LIKE_POST,
  AUTH,
  LOGOUT,
  SIGN_UP,
  SIGN_IN,
};
